### PR TITLE
Moved to GPU

### PR DESCRIPTION
**Pull request by jayavanth**

### CODE REVIEW

**Comment by darkstar112358** [comment]
Can you add a `cuda` command line argument to the `eval` argparser and do your `.cuda()` only when the `.cuda` in `args` is 1.

**Comment by jayavanth** [comment]
done ^

**Comment by darkstar112358** [comment]
Made some cosmetic changes, can you test it on your GPU one final time to verify everything is good.

**Comment by jayavanth** [comment]
ok

**Comment by jayavanth** [comment]
looks okay to me

**Comment by darkstar112358** [comment]
Great, thanks for the help.

**Pull request merged**
